services:
  - type: web
    name: critstrike
    env: node
    buildCommand: npm install && ls -la
    startCommand: node ./server.js
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 3000
      - key: DEPLOY_TIMESTAMP
        value: "2026-05-26-fix-render-deploy"
